### ISSUE TITLE
Image is missing in asset folder

### ISSUE THREAD

**Issue by lee-jun-fan** [ufrshubham/spacescape#1]
FlutterError (Unable to load asset: assets/images/ship_A.png) 
https://github.com/ufrshubham/spacescape/issues/1#issue-945306629
assets/images/simpleSpace_tilesheet@2.png
 assets/images/icon_plusSmall.png
assets/images/icon_plusSmall.png

**Comment by ufrshubham** [comment]
I am not the owner of those assets, so probably it is not a good idea to redistribute them through this repo. Please read the [readme](https://github.com/ufrshubham/spacescape/blob/main/assets/images/README.md) file located under assets/images. You'll get links to original source of those assets.
