### ISSUE TITLE
Screen frozen when restarting after game over

### ISSUE THREAD

**Issue by advandenoord** [ufrshubham/spacescape#14]
When the game is ended because I run out of health and I want to restart the game (play another time), the screen is frozen in the last frame of the previous game. 

I am running the game with the following specs:

Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (3 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1

I have just copied this repo and updated the packages so that it runs with the above specs.

Can you please help me with this?

Many thanks in advance.

**Comment by advandenoord** [comment]
Added "gameRef.resumeEngine();" at the exit button fixed it.

**Comment by ufrshubham** [comment]
@advandenoord thanks for pointing out this problem. Apparently this [commit](https://github.com/ufrshubham/spacescape/commit/8b7fa5df307ee75d9d424dcc05602965a5502f6e) had fixed same problem in pause menu, but game over menu was missed.
